source $HOME/.bash/aliases.sh
source $HOME/.bash/archive.sh
source $HOME/.bash/bundler.sh
source $HOME/.bash/cd.sh
source $HOME/.bash/development.sh
source $HOME/.bash/file.sh
source $HOME/.bash/functions.sh
source $HOME/.bash/general.sh
source $HOME/.bash/git.sh
source $HOME/.bash/other.sh
source $HOME/.bash/path.sh
source $HOME/.bash/prompt.sh
source $HOME/.bash/vagrant.sh
source $HOME/.bash/web.sh
